## 官网按钮显示文字
gw_text=仓库: https://github.com/mkzi-nya/heom
## 官网地址
gw_url=https://github.com/mkzi-nya/heom
## 配置保存目录名字
pz_path=ime_data_dir
## 默认配置名字
pz_zip_name=nya.tar
# 支付宝赞助图片 
zfb_url=https://mkzi-nya.github.io/heom/mikupay.jpg
# 微信赞助图片
wx_url=https://mkzi-nya.github.io/heom/mikupay.jpg
# 是否显示输入方案切换
input_show=1
# 是否显示赞助按钮
zz_show=1
# 是否显示首页详情
sy_detail=1
# 是否显示首页权限按钮
sy_permission=1
# 总是解压配置【默认0】
pz_always_extract=1
# 解压配置时是否强制删除文件【只保留白名单】
pz_extract_delete=1
# 是否显示首页分割符
sy_section_title=1
# 修改基本设置第9个按钮的文本
base_text_9=双检索
# 内置配置白名单
pz_white_list=ime.android.ini;ziti.ttf;用户.txt;